### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Bind** [Bind/forge-jig#4]
- [ ] get automatic changeset releases working
- [ ] get built lib to include yargs cmdDir
- [ ] build script "get" to print out the storage address of a variable to the cli
- [ ] actually working cli when no arguments are passed
- [ ] pretty code output.
